# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_games', '0002_hitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('session_id', models.TextField(primary_key=True, serialize=False)),
                ('progress_bar', models.FloatField()),
            ],
        ),
    ]
