# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_games', '0003_progressbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'email_table',
            },
        ),
    ]
