# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_games', '0004_emailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
